import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import { Header } from "@/app/components/header/index";
import { Footer } from "@/app/components/footer/footer";
import BootstrapClient from "./components/bootsrapclient";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body>
        <BootstrapClient/>
        <Header/>
        <div className="container mb-2">{children}</div>
        <Footer/>
      </body>
    </html>
  );
}
